### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jerviedog** [coin-or/CHiPPS-BiCePS#11]
Dear colleagues,

When I tried to build CHiPPS-BiCePS, I encounteded an error:

Bcps/Bcps/src/BcpsObjectPool.cpp:27:22: error: 'AlpsKnowledgePoolTypeUndefined' was not declared in this scope
   :AlpsKnowledgePool(AlpsKnowledgePoolTypeUndefined) {

The Alps was successfully built by using coinbrew. I checked the Alps.h and AlpsKnowledgePool.h. I couldn't find the definition of AlpsKnowledgePoolTypeUndefined, although I found something like AlpsKnowledgeTypeUndefined.

**Comment by tkralphs** [comment]
It's most likely a mismatch of versions. Perhaps the Dependencies are wrong. If you could say what specific commands you used to build, I will check it.

**Comment by jerviedog** [comment]
I started a fresh repo and built it with coinbrew.
I was using these commands:
```
git clone https://github.com/coin-or/COIN-OR-OptimizationSuite
cd COIN-OR-OptimizationSuite
git clone https://www.github.com/coin-or/coinbrew
coinbrew/coinbrew fetch --main-proj=CHiPPS-BiCePS --skip-update
coinbrew/coinbrew build --main-proj=CHiPPS-BiCePS --prefix=/opt/cpp/opt/coin-or --parallel-jobs=8 --test
```

This time, the error was:
```
g++ -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long -DBCPS_BUILD -o .libs/unitTest BlisBranchObjectInt.o BlisBranchStrategyPseudo.o BlisConGenerator.o BlisConstraint.o BlisHelp.o BlisHeurRound.o BlisMain.o BlisMessage.o BlisModel.o BlisObjectInt.o BlisParams.o BlisPseudo.o BlisTreeNode.o  ../src/.libs/libBcps.so -L/opt/cpp/opt/coin-or/lib -L/usr/lib/gcc/x86_64-linux-gnu/6 -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/6/../../.. /home/image/software/cpp/opt/coin2/COIN-OR-OptimizationSuite/build/Cgl/0.59/src/.libs/libCgl.so /home/image/software/cpp/opt/coin2/COIN-OR-OptimizationSuite/build/Clp/1.16/src/OsiClp/.libs/libOsiClp.so /home/image/software/cpp/opt/coin2/COIN-OR-OptimizationSuite/build/Clp/1.16/src/.libs/libClpSolver.so /home/image/software/cpp/opt/coin2/COIN-OR-OptimizationSuite/build/Clp/1.16/src/.libs/libClp.so /opt/cpp/opt/coin-or/lib/libcoinasl.so /opt/cpp/opt/coin-or/lib/libcoinmumps.so -L/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lgfortran -lquadmath /home/image/software/cpp/opt/coin2/COIN-OR-OptimizationSuite/build/Osi/0.107/src/Osi/.libs/libOsi.so /home/image/software/cpp/opt/coin2/COIN-OR-OptimizationSuite/build/Alps/master/src/.libs/libAlps.so /home/image/software/cpp/opt/coin2/COIN-OR-OptimizationSuite/build/CoinUtils/master/src/.libs/libCoinUtils.so -lbz2 -lz -lblas /opt/cpp/opt/coin-or/lib/libcoinglpk.so -ldl -lm -Wl,--rpath -Wl,/opt/cpp/opt/coin-or/lib
creating unitTest
./unitTest -Alps_instance ./flugpl.mps
/home/image/software/cpp/opt/coin2/COIN-OR-OptimizationSuite/build/Bcps/master/test/.libs/lt-unitTest: symbol lookup error: /home/image/software/cpp/opt/coin2/COIN-OR-OptimizationSuite/build/Bcps/master/src/.libs/libBcps.so.0: undefined symbol: _ZTV12AlpsTreeNode
```

**Comment by tkralphs** [comment]
I couldn't replicate this. It worked fine for me. In general, if you fetch with `--skip-updates`, you may end up with incompatible versions, since one purpose of the fetch is to ensure that a proper set of compatible versions is checked out for building that particular version of that particular project. If you are building multiple projects (which you seem to be doing) and installing everything to the same prefix, you will likely get some issues arising, since the COIN projects that use CHiPPS are not all compatible with the current master. The master of CHiPPS-BLIS is not compatible with the masters of CHiPPS-BiCePS and CHiPPS-ALPS, for example. This is because we made some changes and introduced new stables of those projects for use in another project, but some older projects still depend on the previous versions.

the Optimization Suite contains a mutually compatible set of versions of all projects, so if you want to work with multiple projects, you could just stick to doing the fetch using the Dependencies of the Optimization Suite and the do the build and install of individual projects, as desired. I hope that makes sense.

**Comment by jerviedog** [comment]
That makes sense. Thanks very much:)
